variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:24.0.5-dind
    
stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - dotnet restore
    - dotnet test --logger trx;LogFileName=/test-results/results.trx